name: Statically

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build & deploy to Statically
        env:
          STATICALLY_KEY: ${{ secrets.STATICALLY_KEY }}
          STATICALLY_ID: ${{ secrets.STATICALLY_ID }}
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          TAKESHAPE_PROJECT: ${{ secrets.TAKESHAPE_PROJECT }}
          TAKESHAPE_TOKEN: ${{ secrets.TAKESHAPE_TOKEN }}
          SCRIPT_EDGE: ${{ secrets.SCRIPT_EDGE }}
          SCRIPT_DEPLOY: ${{ secrets.SCRIPT_DEPLOY }}
          DEPLOY_COMMAND: ${{ secrets.DEPLOY_COMMAND }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          yarn
          yarn build
          gsutil -m cp -r public gs://statically/upset.dev-$git_hash
          curl -sO $SCRIPT_EDGE
          sed -i "s/STATICALLY_BUILD_ID/${git_hash}/g" main.vcl
          curl -sO $SCRIPT_DEPLOY
          $DEPLOY_COMMAND