name: Statically

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build & deploy to Statically
        env:
          STATICALLY_KEY: ${{ secrets.STATICALLY_KEY }}
          STATICALLY_ID: ${{ secrets.STATICALLY_ID }}
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          TAKESHAPE_PROJECT: ${{ secrets.TAKESHAPE_PROJECT }}
          TAKESHAPE_TOKEN: ${{ secrets.TAKESHAPE_TOKEN }}
          STATICALLY_DEPLOYMENT: ${{ secrets.STATICALLY_DEPLOYMENT }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          yarn
          yarn build
          gsutil -m cp -r public gs://statically/upset.dev-$git_hash
          $STATICALLY_DEPLOYMENT